tokens_definitions = {
    'PROGRAM': r'\binicioDoPrograma\b',
    'END_PROGRAM': r'\bfimDoPrograma\b',
    'INT': r'\bmonstro\b',
    'DECIMAL': r'\btrapezio\b',
    'TEXT': r'\bfrango\b',
    'BOOLEAN': r'\bbarril\b',
    'TRUE': r'\bverdadeiro\b',
    'FALSE': r'\bfalso\b',
    'IF': r'\beleQueQueremos\b',
    'ELSE': r'\bnaoVaiDarNao\b',
    'WHILE': r'\bqueroMais\b',
    'FOR': r'\bmandaMais\b',
    'READ': r'\bleia\b',
    'WRITE': r'\bescreva\b',
    'ASSIGN': r'=',
    'REL_OP': r'menor_igual|maior_igual|igual|diferente|menor|maior',
    'ADD_OP': r'mais|menos',
    'MUL_OP': r'vezes|dividido',
    'MOD_OP': r'modulo', 
    'LPAREN': r'\(',
    'RPAREN': r'\)',
    'LBRACE': r'\{',
    'RBRACE': r'\}',
    'COMMA': r',',
    'SEMI': r';',
    'NUMBER': r'\d+(\.\d+)?',
    'ID': r'[a-zA-Z_][a-zA-Z0-9_]*',
    'STRING': r'"[^"]*"',
    'NEWLINE': r'\n',
    'WHITESPACE': r'[ \t]+'
}