tokens_definitions = {
    'PROGRAM': r'\binicioDoPrograma\b',
    'END_PROGRAM': r'\bfimDoPrograma\b',
    'INT': r'\bmonstro\b',
    'DECIMAL': r'\btrapezio\b',
    'TEXT': r'\bfrango\b',
    'BOOLEAN': r'\bbarril\b',
    'TRUE': r'\btrue\b',
    'FALSE': r'\bfalse\b',
    'IF': r'\beleQueQueremos\b',
    'ELSE': r'\bnaoVaiDarNao\b',
    'WHILE': r'\bqueroMais\b',
    'FOR': r'\bmandaMais\b',
    'READ': r'\bgetMonster\b',
    'WRITE': r'\bshowMeTheShape\b',
    'REL_OP': r'<=|>=|==|!=|<|>',
    'ASSIGN': r'=',
    'ADD_OP': r'\+|\-',
    'MUL_OP': r'\*|/',
    'MOD_OP': r'%',
    'LPAREN': r'\(',
    'RPAREN': r'\)',
    'LBRACE': r'\{',
    'RBRACE': r'\}',
    'COMMA': r',',
    'SEMI': r';',
    'NUMBER': r'\d+(\.\d+)?',
    'ID': r'[a-zA-Z_][a-zA-Z0-9_]*',
    'STRING': r'"[^"]*"',
    'NEWLINE': r'\n',
    'WHITESPACE': r'[ \t]+'
}